### ISSUE TITLE
Migration auf odoo 11

### ISSUE THREAD

**Issue by aschneider1** [Odoo-Austria/odoo-addons#45]
Hallo,
ist eine Migration des Moduls pos_pay_invoice nach odoo 11 geplant?

**Comment by wpichler** [comment]
Hallo,

ist aktuell noch nicht in Planung. Der Aufwand dafür würde sich aber in Grenzen halten. Wir können das gerne für Sie übernehmen, Bitte mich direkt unter wpichler@callino.at dazu kontaktieren
